### ISSUE TITLE
Proper Orthogonal Decomposition (POD) 

### ISSUE THREAD

**Issue by RokyC** [RBniCS/RBniCSx#5]
```python
eigenvalues, modes, _ = rbnicsx.backends.proper_orthogonal_decomposition(
    snapshots_matrix, reduced_problem.inner_product_action, N=Nmax, tol=0.0)
.......
inner_product = ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx
self._inner_product = inner_product
self._inner_product_action = rbnicsx.backends.bilinear_form_action(
            inner_product, part="real")
```
　　Hello, I noticed that the inner product used in order reduction with the POD method is the partial differential term "▽u", but in the tutorial, it should be the corresponding parameter solution - displacement term "u". I'm a little confused about this
　　![image](https://user-images.githubusercontent.com/59686187/191033970-c2cf114d-bce7-4567-bba0-1152e4ded7d8.png)

**Comment by francesco-ballarin** [comment]
The key point is in the subscript $\mathbb{V}$ in $(., .)_{\mathbb{V}}$ and $\left|\left| . \right|\right|\_{\mathbb{V}}$. You have to choose a inner product for the space $\mathbb{V}$. Since in the example you have copied the code from $\mathbb{V} = H^1_0(\Omega)$, then
```
inner_product = ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx
```
is indeed an inner product for $\mathbb{V}$. There are of course other possible choices, and you are welcome to try them.

The one you are proposing, i.e.
```
inner_product = ufl.inner(u, v) * ufl.dx
```
has many merits, and it is widely used in practice, but it is not an inner product for $\mathbb{V} = H^1_0(\Omega)$. Again, do try it!

**Comment by francesco-ballarin** [comment]
Sure, no worries. In future, for questions like this one you may want to use the "Discussion" section rather than opening an issue. The advantage of opening a discussion is that (1) you do not need to close the issue once solved, and (2) you may mark a reply as answer; the combination of (1) and (2) means that future users who might have the same question could more easily find the answer in the discussion section rather than here in the issues.
